# Generated by Django 5.2.7 on 2025-10-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('study', 'Study'), ('fitness', 'Fitness'), ('work', 'Work'), ('habit', 'Habit'), ('daily routine', 'Daily Routine'), ('self care', 'Self Care'), ('other', 'Other')], max_length=40)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=30)),
                ('reward_xp', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
