# Generated by Django 5.2.7 on 2025-10-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_task_date_created_alter_task_reward_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('mix', 'Mix'), ('study', 'Study'), ('fitness', 'Fitness'), ('work', 'Work'), ('habit', 'Habit'), ('daily routine', 'Daily Routine'), ('self care', 'Self Care'), ('other', 'Other')], default='mix', max_length=40)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.project'),
            preserve_default=False,
        ),
    ]
