# Generated by Django 5.2.7 on 2025-10-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_project_remove_task_category_task_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Quest',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='quest',
        ),
    ]
