# Generated by Django 5.2.7 on 2025-10-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_project_quest_rename_project_task_quest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='project_id',
            new_name='quest_id',
        ),
    ]
