# Generated by Django 5.2.7 on 2025-10-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_quest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('achievment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('condition', models.CharField(blank=True, max_length=75, null=True)),
                ('reward_xp', models.IntegerField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achievements/')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('min_xp', models.IntegerField()),
                ('badge_icon', models.ImageField(blank=True, null=True, upload_to='ranks/')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='streak_days',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_xp',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='achievments',
            field=models.ManyToManyField(blank=True, to='main_app.achievment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rank'),
        ),
    ]
