# Generated by Django 5.2.7 on 2025-10-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_achievment_rank_remove_userprofile_streak_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
